import React from 'react';
import {AbsoluteFill,Audio,Sequence,interpolate,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import {Slide,slides,slidesV2} from './video';
import timing from '../../../data/promo-voiceover-timing.json';
export type PromoProps={indices:number[];music:string;voice?:string;version?:1|2};
type VoiceTiming={role?:string;startFrame:number;durationFrames:number;transcript:string;segments:{from:number;to:number;text:string}[]};
const voiceovers=timing.voiceovers as Record<string,VoiceTiming>;
const VoiceCaption:React.FC<{voice:string}>=({voice})=>{const frame=useCurrentFrame();const item=voiceovers[voice];const player=item.role==='player';const accent=player?'#45c7f4':'#e8b93b';const label=player?'PLAYER PERSPECTIVE · SCRIPTED GAMEPLAY PROMO':'ZACH · SHOP TEACHER & BUSINESS MENTOR';const segment=item.segments.find(x=>frame>=x.from&&frame<x.to);const progress=interpolate(frame,[0,item.durationFrames],[0,100],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <div style={{position:'absolute',zIndex:20,left:'6%',right:'6%',bottom:'7%',background:'rgba(5,8,12,.96)',border:`4px solid ${accent}`,boxShadow:'8px 8px 0 #000',padding:'20px 24px',fontFamily:'Arial, sans-serif'}}><div style={{color:accent,fontWeight:900,fontSize:24,letterSpacing:3}}>{label}</div><div style={{color:'#fff',fontWeight:800,fontSize:38,lineHeight:1.2,marginTop:8}}>{segment?.text||item.transcript}</div><div style={{height:6,background:'#263039',marginTop:14}}><div style={{height:'100%',width:`${progress}%`,background:player?'#45c7f4':'#3fd08a'}}/></div></div>};
export const Promo:React.FC<PromoProps>=({indices,music,voice,version=1})=>{const {durationInFrames}=useVideoConfig();const segment=Math.floor(durationInFrames/indices.length);const item=voice?voiceovers[voice]:null;const source=version===2?slidesV2:slides;return <AbsoluteFill style={{background:'#05070a'}}><Audio src={staticFile(`audio/${music}.mp3`)} volume={(f)=>{const base=interpolate(f,[0,30,durationInFrames-30,durationInFrames-1],[0,.3,.3,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return item&&f>=item.startFrame&&f<item.startFrame+item.durationFrames?base*.35:base;}}/>{voice&&item&&<Sequence from={item.startFrame} durationInFrames={item.durationFrames}><Audio src={staticFile(`audio/${voice}.mp3`)} volume={.95}/><VoiceCaption voice={voice}/></Sequence>}{indices.map((slideIndex,index)=>{const [src,title,copy]=source[slideIndex];const duration=index===indices.length-1?durationInFrames-index*segment:segment;return <Sequence key={src} from={index*segment} durationInFrames={duration}><Slide src={src} title={title} copy={copy} index={index} duration={duration}/></Sequence>})}</AbsoluteFill>};
